version: "3"

services:     
    dj:
        build: django
        command: >
            sh -c "python3 manage.py runserver 0.0.0.0:8000"
        volumes:
        - ./django:/django
        ports:
        - "8000:8000"
        environment: 
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=Testpassword123456
        depends_on: 
            - db

    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Testpassword123456