# Generated by Django 3.1.2 on 2021-02-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='products/images')),
                ('image_url', models.URLField(blank=True)),
                ('song', models.CharField(blank=True, max_length=50)),
                ('artist', models.CharField(blank=True, max_length=50)),
                ('album', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('file_upload', models.FileField(upload_to='products/files')),
                ('file_link', models.URLField(blank=True)),
                ('catagory', models.CharField(choices=[('Transcriptions', 'Transcriptions'), ('Lessons', 'Lessons'), ('Stems', 'Stems')], default='Transcriptions', max_length=20)),
            ],
        ),
    ]
