# Generated by Django 3.1.3 on 2021-10-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211001_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_items_id',
            field=models.CharField(max_length=30),
        ),
    ]
