# Generated by Django 3.1.3 on 2021-10-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211002_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_upload',
        ),
        migrations.AlterField(
            model_name='product',
            name='file_link',
            field=models.URLField(),
        ),
    ]
